spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zichi?useUnicode=true&amp;characterEncoding=utf-8
    name: zichi
    username: zichi
    password: ZiChi66666!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8

image.save.root.path: /home/admin/app/zc/images

logging:
  file:/home/admin/app/zc/logs/zc.log
  