spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/demo?useUnicode=true&amp;characterEncoding=utf-8
    name: demo
    username: lzxtest
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
      uri-encoding: UTF-8
    multipart:
          enabled: true
          max-file-size: 2MB
          max-request-size: 3MB

mybatis:
  typeAliasesPackage: com.zc.**.dataobject
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level:
    root: INFO
    com.zc.acl.domain.dao: debug
    com.zc.biz.customer.domain.dao: debug

security:
  headers:
    frame: false

image.save.root.path: /Users/liangzixing/tmp






