spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/demo?useUnicode=true&amp;characterEncoding=utf-8
    name: demo
    username: lzxtest
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: utf-8

logging:
  level:
    com.zc.acl.domain.dao: debug
    com.zc.biz.customer.domain.dao: debug

image.save.root.path: /Users/liangzixing/tmp